"""s6_posts_v5_fields

Revision ID: 0fa8bc936ad9
Revises: 61cb8cc42130
Create Date: 2026-05-11 15:04:57.995353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa8bc936ad9'
down_revision: Union[str, Sequence[str], None] = '61cb8cc42130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cover_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_prompt', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('buy_rating', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('suitable_for', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('not_suitable_for', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('key_risks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('wait_for', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('themes_summary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('playtime_buckets_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('playtime_buckets_json')
        batch_op.drop_column('themes_summary')
        batch_op.drop_column('wait_for')
        batch_op.drop_column('key_risks')
        batch_op.drop_column('not_suitable_for')
        batch_op.drop_column('suitable_for')
        batch_op.drop_column('buy_rating')
        batch_op.drop_column('comment_prompt')
        batch_op.drop_column('cover_text')
        batch_op.drop_column('pages')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
