"""s5_review_theme_stats_daily_review_stats_signal_types

Revision ID: 61cb8cc42130
Revises: d6df8f392d34
Create Date: 2026-05-11 14:45:36.840386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cb8cc42130'
down_revision: Union[str, Sequence[str], None] = 'd6df8f392d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_review_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('pos_count', sa.Integer(), nullable=True),
    sa.Column('neg_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('daily_pos_rate', sa.Float(), nullable=True),
    sa.Column('rolling_7d_pos_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_review_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_review_stats_appid'), ['appid'], unique=False)

    op.create_table('review_theme_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=32), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('share_pct', sa.Integer(), nullable=False),
    sa.Column('sample_quote', sa.String(length=256), nullable=True),
    sa.Column('total_analyzed', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_theme_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_theme_stats_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_theme_stats_appid'), ['appid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_theme_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_theme_stats_appid'))
        batch_op.drop_index(batch_op.f('ix_review_theme_stats_analyzed_at'))

    op.drop_table('review_theme_stats')
    with op.batch_alter_table('daily_review_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_review_stats_appid'))

    op.drop_table('daily_review_stats')
    # ### end Alembic commands ###
