"""s8_price_snapshots

Revision ID: afdc526a7e43
Revises: 0fa8bc936ad9
Create Date: 2026-05-11 22:56:39.399550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdc526a7e43'
down_revision: Union[str, Sequence[str], None] = '0fa8bc936ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=32), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('historic_low', sa.Float(), nullable=True),
    sa.Column('pct_above_low', sa.Float(), nullable=True),
    sa.Column('is_at_historic_low', sa.Boolean(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_appid'), ['appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_snapshots_pipeline_run_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_appid'))

    op.drop_table('price_snapshots')
    # ### end Alembic commands ###
