"""add post objective_snapshot field

Revision ID: b29461fa0785
Revises: afdc526a7e43
Create Date: 2026-06-07 21:35:55.085972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29461fa0785'
down_revision: Union[str, Sequence[str], None] = 'afdc526a7e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('objective_snapshot')

    # ### end Alembic commands ###
