"""initial schema

Revision ID: d6df8f392d34
Revises: 
Create Date: 2026-05-09 23:47:21.852153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6df8f392d34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exemplar_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_platform', sa.Enum('XIAOHONGSHU', 'WEIBO', 'BILIBILI', 'MANUAL', name='exemplarsource'), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('template_match', sa.String(length=64), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('engagement_metrics', sa.JSON(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('added_by', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exemplar_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exemplar_posts_template_match'), ['template_match'], unique=False)

    op.create_table('game_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=32), nullable=False),
    sa.Column('game_name', sa.String(length=256), nullable=False),
    sa.Column('signal_type', sa.Enum('NEGATIVE_BURST', 'POSITIVE_BURST', 'PLAYER_SPIKE', 'NEW_RELEASE_SPIKE', 'REVIEW_SURGE', name='signaltype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('URGENT', 'NORMAL', 'LOW', name='severity'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_signals_appid'), ['appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_signals_detected_at'), ['detected_at'], unique=False)

    op.create_table('meme_phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=False),
    sa.Column('language', sa.Enum('ZH', 'EN', name='language'), nullable=False),
    sa.Column('source_platform', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('RISING', 'PEAK', 'DECAYING', 'DEAD', name='memestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meme_phrases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meme_phrases_phrase'), ['phrase'], unique=True)
        batch_op.create_index(batch_op.f('ix_meme_phrases_status'), ['status'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_type', sa.Enum('TREND', 'CONTENT', name='pipelinetype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='pipelinestatus'), nullable=True),
    sa.Column('posts_generated', sa.Integer(), nullable=False),
    sa.Column('total_llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_template_name'), ['template_name'], unique=False)

    op.create_table('watchlist',
    sa.Column('appid', sa.String(length=32), nullable=False),
    sa.Column('game_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WATCH', 'DEAD', name='watchstatus'), nullable=False),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_no_signal_count', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('SIGNAL_JUDGMENT', 'TREND_EXTRACTION', 'TRANSLATION', 'COPYWRITING', 'REWRITE', 'EXEMPLAR_TAGGING', name='llmpurpose'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('template_used', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('trigger_entity_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_entity_name', sa.String(length=256), nullable=True),
    sa.Column('trigger_signals', sa.JSON(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('used_meme_phrases', sa.JSON(), nullable=True),
    sa.Column('used_exemplar_ids', sa.JSON(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'ITERATING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', name='poststate'), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('review_iterations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('edit_notes', sa.Text(), nullable=True),
    sa.Column('views_24h', sa.Integer(), nullable=True),
    sa.Column('likes_24h', sa.Integer(), nullable=True),
    sa.Column('saves_24h', sa.Integer(), nullable=True),
    sa.Column('comments_24h', sa.Integer(), nullable=True),
    sa.Column('views_7d', sa.Integer(), nullable=True),
    sa.Column('likes_7d', sa.Integer(), nullable=True),
    sa.Column('saves_7d', sa.Integer(), nullable=True),
    sa.Column('comments_7d', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_state'))

    op.drop_table('posts')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_pipeline_run_id'))

    op.drop_table('llm_calls')
    op.drop_table('watchlist')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_template_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_is_active'))

    op.drop_table('prompt_versions')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('meme_phrases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meme_phrases_status'))
        batch_op.drop_index(batch_op.f('ix_meme_phrases_phrase'))

    op.drop_table('meme_phrases')
    with op.batch_alter_table('game_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_signals_detected_at'))
        batch_op.drop_index(batch_op.f('ix_game_signals_appid'))

    op.drop_table('game_signals')
    with op.batch_alter_table('exemplar_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exemplar_posts_template_match'))

    op.drop_table('exemplar_posts')
    # ### end Alembic commands ###
